const POSE_LANDMARKS_CENTER = {
  NOSE: 0,
};

const POSE_LANDMARKS_LEFT = {
  LEFT_SHOULDER: 11,
  LEFT_ELBOW: 13,
  LEFT_WRIST: 15,
  LEFT_HIP: 23,
  LEFT_KNEE: 25,
  LEFT_ANKLE: 27,
};

const POSE_LANDMARKS_RIGHT = {
  RIGHT_SHOULDER: 12,
  RIGHT_ELBOW: 14,
  RIGHT_WRIST: 16,
  RIGHT_HIP: 24,
  RIGHT_KNEE: 26,
  RIGHT_ANKLE: 28,
};

export { POSE_LANDMARKS_CENTER, POSE_LANDMARKS_LEFT, POSE_LANDMARKS_RIGHT };
